package com.example.domain.database2;

import java.util.Date;

public class NotifyResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.group_id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.user_id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.picture_time
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private Date pictureTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.camera_id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private String cameraId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.score
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private Long score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.creator
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.last_modifier
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private String lastModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.create_time
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.last_modify_time
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.status
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_result.uniq_index_lock
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    private Long uniqIndexLock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.id
     *
     * @return the value of notify_result.id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.id
     *
     * @param id the value for notify_result.id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.group_id
     *
     * @return the value of notify_result.group_id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.group_id
     *
     * @param groupId the value for notify_result.group_id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.user_id
     *
     * @return the value of notify_result.user_id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.user_id
     *
     * @param userId the value for notify_result.user_id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.picture_time
     *
     * @return the value of notify_result.picture_time
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public Date getPictureTime() {
        return pictureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.picture_time
     *
     * @param pictureTime the value for notify_result.picture_time
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setPictureTime(Date pictureTime) {
        this.pictureTime = pictureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.camera_id
     *
     * @return the value of notify_result.camera_id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public String getCameraId() {
        return cameraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.camera_id
     *
     * @param cameraId the value for notify_result.camera_id
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setCameraId(String cameraId) {
        this.cameraId = cameraId == null ? null : cameraId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.score
     *
     * @return the value of notify_result.score
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.score
     *
     * @param score the value for notify_result.score
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setScore(Long score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.creator
     *
     * @return the value of notify_result.creator
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.creator
     *
     * @param creator the value for notify_result.creator
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.last_modifier
     *
     * @return the value of notify_result.last_modifier
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public String getLastModifier() {
        return lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.last_modifier
     *
     * @param lastModifier the value for notify_result.last_modifier
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setLastModifier(String lastModifier) {
        this.lastModifier = lastModifier == null ? null : lastModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.create_time
     *
     * @return the value of notify_result.create_time
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.create_time
     *
     * @param createTime the value for notify_result.create_time
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.last_modify_time
     *
     * @return the value of notify_result.last_modify_time
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.last_modify_time
     *
     * @param lastModifyTime the value for notify_result.last_modify_time
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.status
     *
     * @return the value of notify_result.status
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.status
     *
     * @param status the value for notify_result.status
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_result.uniq_index_lock
     *
     * @return the value of notify_result.uniq_index_lock
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public Long getUniqIndexLock() {
        return uniqIndexLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_result.uniq_index_lock
     *
     * @param uniqIndexLock the value for notify_result.uniq_index_lock
     *
     * @mbg.generated Mon Dec 02 13:39:52 CST 2019
     */
    public void setUniqIndexLock(Long uniqIndexLock) {
        this.uniqIndexLock = uniqIndexLock;
    }
}